//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vacation.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VactionsystemEntities : DbContext
    {
        public VactionsystemEntities()
            : base("name=VactionsystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<userrole> userroles { get; set; }
        public virtual DbSet<vaction> vactions { get; set; }
        public virtual DbSet<vactioncridit> vactioncridits { get; set; }
    }
}
